import io
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from services.storage_service import upload_pdf_to_cloudinary
import models

async def generate_and_upload_evidence_report(alert: models.BombAlert, business: models.Business, sessions: list) -> str:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    
    sub_title_style = styles['Heading2']
    normal_style = styles['Normal']
    
    red_style = ParagraphStyle('RedVerdict', parent=styles['Heading2'], textColor=colors.red, alignment=1)
    yellow_style = ParagraphStyle('YellowVerdict', parent=styles['Heading2'], textColor=colors.orange, alignment=1)
    
    Story = []
    
    # Title
    Story.append(Paragraph("GlowQR Review Fraud Evidence Report", title_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Business Details
    Story.append(Paragraph(f"<b>Business Name:</b> {business.name}", normal_style))
    Story.append(Paragraph(f"<b>Business ID:</b> {business.id}", normal_style))
    Story.append(Paragraph(f"<b>Detection Time:</b> {alert.triggered_at.strftime('%Y-%m-%d %H:%M:%S UTC')}", normal_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Risk Score & Verdict
    v_style = red_style if alert.alert_level == 'red' else yellow_style
    Story.append(Paragraph(f"Risk Score: {alert.risk_score}/100", v_style))
    Story.append(Paragraph(f"Verdict: {alert.verdict.replace('_', ' ').upper()} (Alert Level: {alert.alert_level.upper()})", v_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Reasons
    Story.append(Paragraph("<b>Detection Reasons:</b>", sub_title_style))
    for reason in (alert.reasons or []):
        Story.append(Paragraph(f"• {reason}", normal_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Recommended Actions
    Story.append(Paragraph("<b>Recommended Actions:</b>", sub_title_style))
    actions = [
        "Check your Google Business Profile for new 1-star reviews",
        "Use the 'Flag as inappropriate' option on each suspicious review",
        "Attach this report when contacting Google Business Support",
        "Brief your team — this appears to be a coordinated attack",
        "Contact GlowQR admin for further assistance"
    ]
    for action in actions:
        Story.append(Paragraph(f"→ {action}", normal_style))
    Story.append(Spacer(1, 0.2 * inch))
    
    # Table of Sessions
    Story.append(Paragraph("<b>Flagged Sessions Log:</b>", sub_title_style))
    
    table_data = [["Session ID", "Time", "IP (Masked)", "Device", "Secs to Rate", "Rating"]]
    for s in sessions:
        ip = (s.ip_address[:3] + "***") if s.ip_address else "N/A"
        device = (s.device_fingerprint[:8] + "...") if s.device_fingerprint else "N/A"
        time_str = s.scan_timestamp.strftime('%H:%M:%S') if s.scan_timestamp else "N/A"
        rating = str(s.overall_rating) if s.overall_rating else "N/A"
        secs = str(s.time_to_rate_seconds) if s.time_to_rate_seconds is not None else "N/A"
        
        table_data.append([str(s.id)[:8], time_str, ip, device, secs, rating])
        
    t = Table(table_data, colWidths=[1*inch, 1*inch, 1*inch, 1.2*inch, 0.8*inch, 0.8*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.beige),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ]))
    Story.append(t)
    Story.append(Spacer(1, 0.5 * inch))
    
    # Footer
    footer_text = f"Generated by GlowQR · {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')} · This report is confidential and intended for the business owner only."
    Story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray, alignment=1)))
    
    doc.build(Story)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    url = await upload_pdf_to_cloudinary(pdf_bytes, business.id, str(alert.id))
    return url
